// Code generated by goctl. DO NOT EDIT.
package types

type ValidateReq struct {
	Txt  string `json:"txt"`
	Hash string `json:"hash,optional"`
}

type ValidateReply struct {
	IsValidate bool   `json:"is_validate"`
	BadWord    string `json:"bad_word"`
}

type FindReq struct {
	Txt     string `json:"txt"`
	Channel string `json:"channel"`
	Hash    string `json:"hash,optional"`
}

type FindReply struct {
	IsValidate bool                `json:"is_validate"`
	BadWords   map[string][]string `json:"bad_words"`
}

type BatchItemReq struct {
	DataId  string `json:"data_id"`
	Txt     string `json:"txt"`
	Channel string `json:"channel"`
	Hash    string `json:"hash,optional"`
}

type BatchFindReq struct {
	Items []BatchItemReq `json:"items"`
}

type BatchItemReply struct {
	DataId     string              `json:"data_id"`
	Hash       string              `json:"hash"`
	IsValidate bool                `json:"is_validate"`
	BadWords   map[string][]string `json:"bad_words"`
}

type BatchFindReply struct {
	Items map[string]BatchItemReply `json:"items"`
}

type AddWordReq struct {
	Words []string `json:"words"`
}

type AddWordReply struct {
}

type DeleteWordReq struct {
	Words []string `json:"words"`
}

type DeleteWordReply struct {
}
